apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitops-demo
  finalizers: []
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  source:
    path: deploy/dev
    repoURL: https://github.com/ChanJinYeon/CI-CD-test.git
    targetRevision: HEAD
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      enabled: true
    syncOptions:
      - CreateNamespace=true

